# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterHybridiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  flutter_application_path = '../flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  # Pods for FlutterHybridiOS

  target 'FlutterHybridiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterHybridiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
