# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterHybridiOSB' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for FlutterHybridiOSB
  
  flutter_application_path = '../flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  target 'FlutterHybridiOSBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterHybridiOSBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
